import { readFile, writeFile } from "node:fs/promises";
import { basename } from "node:path";
import { prepareOutputFile, type PreviewArtifactManifest } from "@just-agent/preview-core";

export type PreviewPublishFormat = "pr-comment" | "readme" | "gallery" | "release-note";

export interface PreviewPublishOptions {
  manifests: PreviewArtifactManifest[];
  format?: PreviewPublishFormat;
  output?: string;
  title?: string;
  description?: string;
  baseUrl?: string;
  repository?: string;
  branch?: string;
  sha?: string;
  workflowRunUrl?: string;
  includeTable?: boolean;
  includeHtmlVideo?: boolean;
  headingLevel?: number;
}

export interface PreviewPublishResult {
  format: PreviewPublishFormat;
  output?: string;
  markdown: string;
  assetCount: number;
}

export async function loadPreviewManifest(path: string): Promise<PreviewArtifactManifest> {
  const raw = await readFile(path, "utf8");
  const manifest = JSON.parse(raw) as PreviewArtifactManifest;
  validateManifest(manifest, path);
  return manifest;
}

export async function loadPreviewManifests(paths: string[]): Promise<PreviewArtifactManifest[]> {
  if (paths.length === 0) {
    throw new Error("At least one manifest path is required.");
  }
  return Promise.all(paths.map((path) => loadPreviewManifest(path)));
}

export function createPreviewPublishMarkdown(options: PreviewPublishOptions): string {
  const format = options.format ?? "pr-comment";
  const manifests = normalizeManifests(options.manifests);

  switch (format) {
    case "pr-comment":
      return createPrCommentMarkdown({ ...options, manifests });
    case "readme":
      return createReadmeMarkdown({ ...options, manifests });
    case "gallery":
      return createGalleryMarkdown({ ...options, manifests });
    case "release-note":
      return createReleaseNoteMarkdown({ ...options, manifests });
  }
}

export async function writePreviewPublishMarkdown(options: PreviewPublishOptions): Promise<PreviewPublishResult> {
  const markdown = createPreviewPublishMarkdown(options);
  const format = options.format ?? "pr-comment";
  let output: string | undefined;

  if (options.output) {
    output = await prepareOutputFile(options.output);
    await writeFile(output, markdown, "utf8");
  }

  return {
    format,
    output,
    markdown,
    assetCount: options.manifests.length
  };
}

function createPrCommentMarkdown(options: RequiredManifests<PreviewPublishOptions>): string {
  const heading = markdownHeading(options.headingLevel ?? 2, options.title ?? "Just-Preview artifacts");
  const description = options.description ?? "Preview assets generated by `just-preview` for this change.";
  const lines = [
    heading,
    "",
    description,
    "",
    createHeroBlock(options),
    "",
    createAssetTable(options),
    "",
    createContextBlock(options),
    "",
    "> Preview what your Agent built."
  ];
  return compactMarkdown(lines);
}

function createReadmeMarkdown(options: RequiredManifests<PreviewPublishOptions>): string {
  const heading = markdownHeading(options.headingLevel ?? 2, options.title ?? "Preview");
  const description = options.description ?? "Generated with Just-Preview, an Agent-native monorepo toolkit for HTML to Video, HTML to Thumbnail, and README Preview Assets.";
  const lines = [
    heading,
    "",
    description,
    "",
    createHeroBlock(options),
    options.includeTable === false ? "" : createAssetTable(options),
    "",
    "_Generated by [Just-Preview](https://github.com/Just-Agent/Just-Product-Preview)._"
  ];
  return compactMarkdown(lines);
}

function createGalleryMarkdown(options: RequiredManifests<PreviewPublishOptions>): string {
  const heading = markdownHeading(options.headingLevel ?? 2, options.title ?? "Preview gallery");
  const lines = [
    heading,
    "",
    options.description ?? "A gallery of generated thumbnails, GIFs, videos, and recipe-based preview artifacts.",
    ""
  ];

  for (const manifest of options.manifests) {
    const asset = describeManifest(manifest, options);
    lines.push(`### ${escapeMarkdown(asset.label)}`);
    lines.push("");
    lines.push(renderAssetEmbed(asset, options));
    lines.push("");
    lines.push(`- Format: \`${asset.format}\``);
    lines.push(`- Source: ${asset.source}`);
    lines.push(`- Viewport: ${asset.viewport}`);
    lines.push(`- Generated: ${asset.generatedAt}`);
    lines.push("");
  }

  lines.push("> Generated by Just-Preview — Preview what your Agent built.");
  return compactMarkdown(lines);
}

function createReleaseNoteMarkdown(options: RequiredManifests<PreviewPublishOptions>): string {
  const heading = markdownHeading(options.headingLevel ?? 2, options.title ?? "Preview assets");
  const lines = [
    heading,
    "",
    options.description ?? "This release includes generated preview assets for README, GitHub PR Preview, and release distribution.",
    "",
    createAssetTable(options),
    ""
  ];

  if (options.workflowRunUrl) {
    lines.push(`Workflow run: ${options.workflowRunUrl}`);
    lines.push("");
  }

  lines.push("_Generated with Just-Preview._");
  return compactMarkdown(lines);
}

function createHeroBlock(options: RequiredManifests<PreviewPublishOptions>): string {
  const primaryImage = options.manifests.find((manifest) => isImageFormat(manifest.output.format) || manifest.output.format === "gif");
  const primaryVideo = options.manifests.find((manifest) => isVideoFormat(manifest.output.format));

  if (primaryImage && primaryVideo) {
    const image = describeManifest(primaryImage, options);
    const video = describeManifest(primaryVideo, options);
    return `[![${escapeMarkdown(image.alt)}](${image.href})](${video.href})`;
  }

  const primary = describeManifest(primaryImage ?? primaryVideo ?? options.manifests[0]!, options);
  return renderAssetEmbed(primary, options);
}

function createAssetTable(options: RequiredManifests<PreviewPublishOptions>): string {
  const rows = options.manifests.map((manifest) => {
    const asset = describeManifest(manifest, options);
    return `| ${escapeMarkdown(asset.label)} | \`${asset.format}\` | ${asset.viewport} | ${asset.source} | [open](${asset.href}) |`;
  });

  return [
    "| Asset | Format | Viewport | Source | Link |",
    "|---|---:|---:|---|---|",
    ...rows
  ].join("\n");
}

function createContextBlock(options: RequiredManifests<PreviewPublishOptions>): string {
  const rows: string[] = [];
  if (options.repository) rows.push(`- Repository: \`${options.repository}\``);
  if (options.branch) rows.push(`- Branch: \`${options.branch}\``);
  if (options.sha) rows.push(`- Commit: \`${options.sha}\``);
  if (options.workflowRunUrl) rows.push(`- Workflow: ${options.workflowRunUrl}`);
  if (rows.length === 0) return "";
  return ["Context", "", ...rows].join("\n");
}

function renderAssetEmbed(asset: DescribedAsset, options: PreviewPublishOptions): string {
  if (isImageFormat(asset.format) || asset.format === "gif") {
    return `![${escapeMarkdown(asset.alt)}](${asset.href})`;
  }

  if (isVideoFormat(asset.format) && options.includeHtmlVideo !== false) {
    return `<video src="${asset.href}" controls muted playsinline width="960"></video>\n\n[Watch preview video](${asset.href})`;
  }

  return `[Open ${escapeMarkdown(asset.label)}](${asset.href})`;
}

interface DescribedAsset {
  label: string;
  alt: string;
  href: string;
  source: string;
  viewport: string;
  format: string;
  generatedAt: string;
}

function describeManifest(manifest: PreviewArtifactManifest, options: PreviewPublishOptions): DescribedAsset {
  const format = manifest.output.format || formatFromFilename(manifest.output.filename);
  const filename = manifest.output.filename || basename(manifest.output.path);
  return {
    label: labelForManifest(manifest),
    alt: `${labelForManifest(manifest)} generated by Just-Preview`,
    href: assetHref(manifest, options),
    source: manifest.source.url,
    viewport: `${manifest.viewport.width}x${manifest.viewport.height}`,
    format,
    generatedAt: manifest.generatedAt,
  };
}

function labelForManifest(manifest: PreviewArtifactManifest): string {
  const command = manifest.command === "gif" ? "GIF preview" : manifest.command === "thumbnail" ? "Thumbnail" : manifest.command === "recipe" ? "Recipe preview" : "Video preview";
  return `${command} (${manifest.output.filename || basename(manifest.output.path)})`;
}

function assetHref(manifest: PreviewArtifactManifest, options: PreviewPublishOptions): string {
  const rawPath = manifest.output.path || manifest.output.filename;
  const filename = manifest.output.filename || basename(rawPath);
  const baseUrl = options.baseUrl?.replace(/\/$/, "");

  if (baseUrl) {
    return `${baseUrl}/${encodePath(filename)}`;
  }

  return normalizeMarkdownPath(rawPath);
}

function normalizeManifests(manifests: PreviewArtifactManifest[]): PreviewArtifactManifest[] {
  if (!Array.isArray(manifests) || manifests.length === 0) {
    throw new Error("At least one preview manifest is required to publish Markdown.");
  }
  return manifests;
}

function validateManifest(manifest: PreviewArtifactManifest, path: string): void {
  if (!manifest || typeof manifest !== "object") throw new Error(`Invalid manifest at ${path}.`);
  if (manifest.tool !== "just-preview") throw new Error(`Manifest ${path} is not a Just-Preview manifest.`);
  if (!manifest.output?.path) throw new Error(`Manifest ${path} is missing output.path.`);
  if (!manifest.source?.url) throw new Error(`Manifest ${path} is missing source.url.`);
  if (!manifest.viewport || typeof manifest.viewport.width !== "number" || typeof manifest.viewport.height !== "number") {
    throw new Error(`Manifest ${path} is missing viewport width/height.`);
  }
}

function markdownHeading(level: number, text: string): string {
  const safeLevel = Math.min(6, Math.max(1, Math.round(level)));
  return `${"#".repeat(safeLevel)} ${text}`;
}

function compactMarkdown(lines: string[]): string {
  return lines
    .map((line) => line.trimEnd())
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd() + "\n";
}

function escapeMarkdown(value: string): string {
  return value.replace(/[\\[\]]/g, "\\$&");
}

function encodePath(value: string): string {
  return value.split("/").map((part) => encodeURIComponent(part)).join("/");
}

function normalizeMarkdownPath(value: string): string {
  return value.replace(/\\/g, "/");
}

function isImageFormat(format: string): boolean {
  return ["png", "jpg", "jpeg", "webp", "svg"].includes(format.toLowerCase());
}

function isVideoFormat(format: string): boolean {
  return ["mp4", "mov", "webm", "m4v"].includes(format.toLowerCase());
}

function formatFromFilename(filename: string): string {
  const match = filename.toLowerCase().match(/\.([a-z0-9]+)$/);
  return match?.[1] ?? "unknown";
}

type RequiredManifests<T extends PreviewPublishOptions> = T & { manifests: PreviewArtifactManifest[] };
