import test from "node:test";
import assert from "node:assert/strict";
import { createPreviewPublishMarkdown, type PreviewPublishOptions } from "./index.js";

const baseOptions: PreviewPublishOptions = {
  manifests: [
    {
      schemaVersion: "1",
      tool: "just-preview",
      version: "0.4.0",
      command: "thumbnail",
      generatedAt: "2026-05-18T00:00:00.000Z",
      source: { url: "https://example.com" },
      output: { path: "outputs/cover.png", filename: "cover.png", format: "png" },
      viewport: { width: 1280, height: 720 }
    },
    {
      schemaVersion: "1",
      tool: "just-preview",
      version: "0.4.0",
      command: "video",
      generatedAt: "2026-05-18T00:00:01.000Z",
      source: { url: "https://example.com" },
      output: { path: "outputs/preview.mp4", filename: "preview.mp4", format: "mp4" },
      viewport: { width: 1280, height: 720 }
    }
  ],
  title: "Preview artifacts",
  baseUrl: "./outputs"
};

test("creates README markdown with linked hero preview", () => {
  const markdown = createPreviewPublishMarkdown({ ...baseOptions, format: "readme" });
  assert.match(markdown, /## Preview artifacts/);
  assert.match(markdown, /cover\.png/);
  assert.match(markdown, /preview\.mp4/);
  assert.match(markdown, /Generated by \[Just-Preview\]/);
});

test("creates PR comment markdown with context", () => {
  const markdown = createPreviewPublishMarkdown({
    ...baseOptions,
    format: "pr-comment",
    repository: "Just-Agent/Just-Product-Preview",
    branch: "main",
    sha: "abc123"
  });
  assert.match(markdown, /Just-Preview artifacts|Preview artifacts/);
  assert.match(markdown, /Repository: `Just-Agent\/Just-Product-Preview`/);
  assert.match(markdown, /Preview what your Agent built/);
});

test("creates gallery markdown", () => {
  const markdown = createPreviewPublishMarkdown({ ...baseOptions, format: "gallery" });
  assert.match(markdown, /Preview gallery|Preview artifacts/);
  assert.match(markdown, /Thumbnail \(cover\.png\)/);
  assert.match(markdown, /Video preview \(preview\.mp4\)/);
});

test("creates release-note markdown", () => {
  const markdown = createPreviewPublishMarkdown({
    ...baseOptions,
    format: "release-note",
    workflowRunUrl: "https://github.com/Just-Agent/Just-Product-Preview/actions/runs/1"
  });
  assert.match(markdown, /Preview artifacts|Preview assets/);
  assert.match(markdown, /Workflow run:/);
  assert.match(markdown, /release distribution|Generated with Just-Preview/);
});
