#!/usr/bin/env node
import { existsSync } from "node:fs";
import { mkdir, readFile, stat } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const cli = join(root, "apps/cli/dist/index.js");
const outputs = join(root, "outputs/smoke-publish");
const manifests = "examples/publish-workflow/manifests/*.manifest.json";
const formats = [
  ["pr-comment", "pr-comment.md", /Preview what your Agent built|Just-Preview artifacts/],
  ["readme", "readme-preview.md", /Generated by \[Just-Preview\]/],
  ["gallery", "preview-gallery.md", /Preview gallery|Preview artifacts/],
  ["release-note", "release-preview.md", /Workflow run|Generated with Just-Preview|release distribution/]
];

await mkdir(outputs, { recursive: true });

if (!existsSync(cli)) {
  throw new Error("CLI is not built. Run pnpm build before pnpm smoke:publish.");
}

for (const [format, filename, expected] of formats) {
  const out = join(outputs, filename);
  const args = ["publish", "--manifest", manifests, "--format", format, "--base-url", "./outputs", "--out", out, "--repo", "Just-Agent/Just-Product-Preview", "--branch", "main", "--sha", "smoke"];
  await run(format, args);
  await assertMarkdown(out, expected);
}

console.log("Smoke publish workflow passed.");

async function run(label, args) {
  console.log(`Running smoke publish ${label}: just-preview ${args.join(" ")}`);
  await new Promise((resolvePromise, reject) => {
    const child = spawn(process.execPath, [cli, ...args], { cwd: root, stdio: "inherit" });
    child.on("exit", (code, signal) => {
      if (signal) reject(new Error(`${label} publish smoke exited from signal ${signal}`));
      else if (code !== 0) reject(new Error(`${label} publish smoke failed with exit code ${code}`));
      else resolvePromise();
    });
  });
}

async function assertMarkdown(path, expected) {
  const info = await stat(path);
  if (info.size < 100) throw new Error(`Publish artifact is too small: ${path}`);
  const text = await readFile(path, "utf8");
  if (!expected.test(text)) throw new Error(`Publish artifact did not match expected content: ${path}`);
}
